from pathlib import Path
from typing import Final

EXPERT_TEMPLATE_ROOT: Final = Path("knowledge/expert_templates")
EXPERT_TEMPLATE_CHUNK_SIZE_TOKENS: Final = 800
EXPERT_TEMPLATE_CHUNK_OVERLAP_TOKENS: Final = 80
EXPERT_TEMPLATE_VECTOR_CANDIDATE_K: Final = 20
EXPERT_TEMPLATE_LEXICAL_CANDIDATE_K: Final = 20
EXPERT_TEMPLATE_TOP_K: Final = 3
EXPERT_TEMPLATE_MAX_CONTEXT_TOKENS: Final = 2500
EXPERT_TEMPLATE_MIN_VECTOR_SCORE: Final = 0.30
